version: '3'

services:
  web:
    image: django_gunicorn_image
    container_name: django_gunicorn_container
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb_container
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env


  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:./pervi_sait/static
#      - media_volume:./media
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
#  media_volume:
