version: '3'

services:
  web:
    command: /app/run.sh
    build:
      context: .
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media

    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    labels:
      - "traefik.http.routers.magazin.rule=Host(`magazin.dev.doomer.ru`)"
      - "traefik.http.services.magazin.loadbalancer.server.port=8080"
      - "--entrypoints.webSecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=denis@doomer.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/django.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
      - ./.docker/logs:/var/logs/nginx:rw
    depends_on:
      - web
    restart: unless-stopped

volumes:
  db_data:
  static_data:
  media_data:
