version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ./static:/usr/src/app/static:rw
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
        magazin_net:
    restart: always
  mysql:
    image: mariadb:10.5.8
    volumes:
      - mysql_ng_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      magazin_net:
    restart: always
networks:
    magazin_net:
        driver: bridge