version: '3'

services:
  web:
    command: /app/run.sh
    build:
      context: .
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/django.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
      - ./.docker/logs:/var/logs/nginx:rw
    depends_on:
      - web
    restart: unless-stopped

volumes:
  db_data:
  static_data:
  media_data:
