---
- name: Deploy Django on Ubuntu
  hosts: django-server
  become: yes
  vars:
    virtualenv_path: myenv/
    django_path: /home/django/magazin
    django_static: /home/django/magazin/static
    project_name: magazin

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install necessary packages
      apt:
        name: ['python3', 'python3-pip', 'python3-venv']
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Create django user without login capabilities
      user:
        name: django
        system: yes
        shell: /usr/sbin/nologin

    - name: Create a virtual environment
      command:
        cmd: "python3 -m venv {{ virtualenv_path }}"
        creates: "{{ virtualenv_path }}"

    - name: Create static directory for Django project
      file:
        path: "{{ django_static }}"
        state: directory
        owner: django
        group: django
        mode: '0755'

    - name: Copy Install requirements
      copy:
        src: ../requirements.txt
        dest: "{{ django_path }}"
        owner: django
        group: django
        mode: '0755'

    - name: Install requirements
      pip:
        requirements: "{{ django_path}}/requirements.txt"
        virtualenv: "{{ virtualenv_path }}"

    - name: Install gunicorn in virtual environment
      pip:
        name: gunicorn
        virtualenv: "{{ virtualenv_path }}"

    - name: Copy Nginx configuration
      copy:
        src: myproject_nginx.conf
        dest: "/etc/nginx/sites-available/{{ project_name }}"

    - name: Copy systemd service file
      copy:
        src: mydjango.service
        dest: /etc/systemd/system/

    - name: Enable Nginx configuration
      file:
        src: "/etc/nginx/sites-available/{{ project_name }}"
        dest: "/etc/nginx/sites-enabled/{{ project_name }}"
        state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted