---
- name: Deploy Django on Ubuntu
  hosts: django-server
  become: yes
  vars:
    virtualenv_path: myenv/
    django_path: /home/django/magazin
    django_static: /home/django/magazin/static
    project_name: magazin

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install necessary packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Install nginx
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Create django user without login capabilities
      user:
        name: django
        system: yes
        shell: /usr/sbin/nologin

    - name: Create static directory for Django project
      file:
        path: "{{ django_static }}"
        state: directory
        owner: django
        group: django
        mode: '0755'

    - name: Copy Install requirements
      copy:
        src: ../requirements.txt
        dest: "{{ django_path }}"
        owner: django
        group: django
        mode: '0755'

    - name: Install requirements
      pip:
        requirements: "{{ django_path}}/requirements.txt"

    - name: Copy Nginx configuration
      copy:
        src: myproject_nginx.conf
        dest: "/etc/nginx/sites-available/{{ project_name }}"

    - name: Copy systemd service file
      copy:
        src: mydjango.service
        dest: /etc/systemd/system/mydjango.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd to recognize new service
      command:
        systemctl daemon-reload

    - name: Enable mydjango.service to start on boot
      systemd:
        name: mydjango
        enabled: yes

    - name: Enable Nginx configuration
      file:
        src: "/etc/nginx/sites-available/{{ project_name }}"
        dest: "/etc/nginx/sites-enabled/{{ project_name }}"
        state: link

    - name: "Запуск Certbot для Nginx"
      command:
         cmd: certbot --nginx -d magazin.dev.doomer.ru --non-interactive --agree-tos --email denis@doomer.ru
         warn: no
      when: certbot_renewal is not defined
      register: certbot_setup

    - name: Установка cron-задачи для автоматического обновления сертификата
      cron:
          name: Certbot Renewal
          minute: "30"
          hour: "2"
          job: "/usr/bin/certbot renew --quiet"
      when: certbot_setup is changed

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted