# Generated by Django 4.1.7 on 2023-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD_auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=200, verbose_name='Марка')),
                ('auto_1', models.CharField(max_length=200, verbose_name='Модель')),
                ('auto_2', models.TextField(verbose_name='Характеристики')),
                ('auto_3', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
