# Generated by Django 4.1.7 on 2023-03-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervi_sait', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BD_auto',
            new_name='Auto',
        ),
    ]
