# Generated by Django 4.1.7 on 2023-06-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pervi_sait', '0003_rename_auto_3_auto_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
