# Generated by Django 4.1.7 on 2023-08-01 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pervi_sait', '0004_auto_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('opisanie', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('foto', models.ImageField(blank=True, upload_to='%Y/%m/%d', verbose_name='Фото')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['create_date'], 'verbose_name': 'автомобили', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.RemoveField(
            model_name='auto',
            name='data',
        ),
        migrations.AddField(
            model_name='auto',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='harakteristika',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.CreateModel(
            name='ZapisTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_auto', models.CharField(max_length=200)),
                ('nomer_auto', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pervi_sait.part')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
