# Generated by Django 4.1.7 on 2023-08-10 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pervi_sait', '0005_part_alter_auto_options_remove_auto_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapisto',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='zapisto',
            name='date',
            field=models.DateTimeField(verbose_name='Выбрать дату и время для записи'),
        ),
    ]
