# Generated by Django 4.1.7 on 2023-08-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervi_sait', '0006_zapisto_create_date_alter_auto_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='data',
            new_name='date',
        ),
    ]
