# Generated by Django 4.1.7 on 2023-08-17 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pervi_sait', '0007_rename_data_part_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
