# Generated by Django 4.1.7 on 2023-08-31 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pervi_sait', '0008_alter_zapisto_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('opisanie', models.TextField(blank=True, verbose_name='Описание колес')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('part', models.ManyToManyField(to='pervi_sait.part')),
            ],
        ),
    ]
