name: Deploy to dev.doomer.ru

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to dev.doomer.ru
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: dev.doomer.ru
        USER: root
        TARGET: /home/django/magazin
      run: |
        # Install SSH client
        sudo apt-get install -y openssh-client
        # Write the private key to a file
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        # Copy the files to the target server
        scp -i private_key -r * $USER@$HOST:$TARGET
        # Run the deployment script on the target server
        ssh -i private_key $USER@$HOST "$TARGET/deploy.sh"
        # Cleanup
        rm -f private_key
