name: Deploy to dev.doomer.ru

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        HOST: dev.doomer.ru
        USERNAME: root
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "$KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no -r . $USERNAME@$HOST:/home/django/magazin
        ssh -i deploy_key -o StrictHostKeyChecking=no $USERNAME@$HOST "systemctl restart mydjango"
        rm -f deploy_key
