name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        HOST: ${{ env.HOST }}
        USER: root
        TARGET_DIR: /home/django/magazin
      run: |
        # Install ssh-agent if not already installed, it is required by Docker.
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )

        # Run ssh-agent (inside the build environment)
        eval $(ssh-agent -s)

        # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
        echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -

        # Use ssh-keyscan to scan the keys of your private server. Replace your_server_ip_or_hostname with your host's IP or domain name.
        mkdir -p ~/.ssh
        ssh-keyscan $HOST >> ~/.ssh/known_hosts

        # Finally, Use rsync (or scp) to deploy your code to the server
        rsync -av --delete . $USER@$HOST:$TARGET_DIR
